### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by LexManos** [Guichaguri/BetterFps#3]
Why are there no unit tests to demonstrate the performance differences between the different algorithms?
Any explanation of why one is better than the other besides anecdotal screenshots?
Looking at your actual functions for cos/sin they all look either the same operations wise or slower than vanilla. 
The only one that seems to be functionally more proficient is RivensMath, because it caches the shifted cos thus removing the need for a addition in each call.

**Comment by Guichaguri** [comment]
I do have unit tests, I just needed to commit them.
All of the algorithms are not mine and I don't want to change them yet, that is because math will not be the "main" improvement of the mod.
What the mod curretly have is just a recode of FPSPlus using ASM with more algorithms.
I'm working on other improvements in vanilla AIs, TEs, rendering, but i'll not start committing yet.
