### ISSUE TITLE
Launcher not detecting installation

### ISSUE THREAD

**Issue by Jake1702** [Guichaguri/BetterFps#55]
* Minecraft Version: 1.11.2
* BetterFps Version: 1.4.3
* Forge/LiteLoader Version (if any): 
* Crash Logs (if any): 
* Other Mods (if any): 
---

When installing BetterFPS to the vanilla launcher, it is not detected as a version, therefore isn't available. Tested on Windows 7, Windows 10 and Ubuntu 16.04 (All 64 bit)

**Comment by Guichaguri** [comment]
Do you have Minecraft vanilla 1.11.2 installed?

**Comment by Jake1702** [comment]
Yes, I do. Also, it doesn't seem to matter whether I have OptiFine on it or not. Extending from OptiFine or Vanilla 1.11.2, neither work. I also tried renaming the folder, json and the id inside the json of the version, but it still isn't showing up and I have no idea why.

**Comment by Guichaguri** [comment]
Are you using the new launcher or the old (java) one?
Which process is not working? The part of the installer where you choose the version to install?

**Comment by Jake1702** [comment]
Well on Ubuntu I have no choice, but on all 3 tests, it was with the old Java launcher. Also, installing it works fine, just that AFTER it's installed, the launcher isn't detecting the version installed.

**Comment by Guichaguri** [comment]
I've just found the problem: The old launcher doesn't know how to parse all of [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) date formats, while the new launcher does.

Format that I was using: `2017-04-22T19:39:47`
Format that the old launcher accepts: `2017-04-22T19:39:47-0300`

Yeah... Just because of five extra characters in the date, the installer isn't working in the old launcher. I'll release a new version with the fix tomorrow :)

**Comment by Guichaguri** [comment]
> I'll release a new version with the fix tomorrow :)

...and I've never released.
Sorry, I totally forgot about it. It's [out](https://minecraft.curseforge.com/projects/betterfps/files/2415906) now
