### ISSUE TITLE
[1.12.1] Start up crash

### ISSUE THREAD

**Issue by TheLimePixel** [Guichaguri/BetterFps#83]
* Minecraft Version: 1.12.1
* BetterFps Version:  1.4.6
* Forge/LiteLoader Version (if any): 14.20.0.2452 
* Crash Logs (if any): https://pastebin.com/MVDc4Gdc (it's the log as there isn't a crash log
* Other Mods (if any): 
---

**Comment by Leo40Git** [comment]
I'm getting the same crash.

**Comment by Guichaguri** [comment]
BetterFps does not support 1.12.1 yet. Use 1.12 instead.

**Comment by jkroepke** [comment]
Do you plan to support 1.12.1?

**Comment by Guichaguri** [comment]
@jkroepke Absolutely, I'll have some free time this weekend that I can use to work on an update

**Comment by jkroepke** [comment]
Awesome!

Am 24.08.2017 um 01:54 schrieb Guichaguri <notifications@github.com>:

@jkroepke <https://github.com/jkroepke> Absolutely, I'll have some free
time this weekend that I can use to work on an update

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Guichaguri/BetterFps/issues/83#issuecomment-324494261>,
or mute the thread

**Comment by Guichaguri** [comment]
Here it is: https://minecraft.curseforge.com/projects/betterfps/files/2469845
